title: "Example EBAII 2023"
author: "Lovely Team"
copytight: 2022
exclude_patterns:
  - _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "**.ipynb"
only_build_toc_files: false


execute:
  execute_notebooks: auto
  cache: ""
  exclude_patterns: []
  timeout: 30
  run_in_temp: false
  allow_errors: false
  stderr_output: show


html:
  favicon: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issue_button: true
  use_multitoc_numberint: true
  extra_navbar: Powered by <a href="https://jupyterhub.cluster.france-bioinformatique.fr">IFB Jupyter</a>
  extra_footer: ""
  home_page_in_navbar: true
  announcement: ""

repository:
  url: https://github.com/IFB-ElixirFr/EBAII
  path_to_book: ""
  branch: master